s=set()

f1=int(input("enter a num: "))
s.add(f1)
f2=int(input("enter a num: "))
s.add(f2)
f3=int(input("enter a num: "))
s.add(f3)
f4=int(input("enter a num: "))
s.add(f4)
f5=int(input("enter a num: "))
s.add(f5)
f6=int(input("enter a num: "))
s.add(f6)
f7=int(input("enter a num: "))
s.add(f7)
f8=int(input("enter a num: "))
s.add(f8)

print(s)